update

diff --git a/bin/castep_analysis b/bin/castep_analysis
--- a/bin/castep_analysis
+++ b/bin/castep_analysis
@@ -74,14 +74,15 @@ function casplit {
 
     # split concatenated castep file
 
-    echo "split $seed.castep files if concatenated ..."
+    echo "split the $seed.castep file if concatenated ..."
 
-    rm -f $seed-split*
+    [[ ! -e $seed.castep ]] && echo "$seed.castep not found ..." && exit 1
 
-    if [[ -e $seed.castep ]]; then
-        csplit -s -z -f $seed -b -split-%02d.castep $seed.castep '/CCC   AA    SSS  TTTTT  EEEEE  PPPP/' {*}
-        rm -f $seed-split-00.castep
-    fi
+    rm -f $seed-run-*.castep
+
+    csplit -s -z -f $seed -b -run-%02d.castep $seed.castep '/CCC   AA    SSS  TTTTT  EEEEE  PPPP/' {*}
+
+    rm -f $seed-run-00.castep
 }
 
 function parsing {
@@ -89,18 +90,18 @@ function parsing {
     # loop over splitted ${seed}.castep file
 
     header='true'
-    for f in $(ls $seed-split-*.castep)
+    for f in $(ls $seed-run-*.castep)
     do
-        seedsplit=${f%%.castep}
+        seedrun=${f%%.castep}
 
-        echo "parsing $seedsplit.castep file ..."
+        echo "parsing $seedrun.castep file ..."
 
         ## get input from ${seed}.castep file
         input=''
-        input=$(sed -n -r '/^ \*+ Title \*+/,/^\+\-+ MEMORY/p' $seedsplit.castep)
+        input=$(sed -n -r '/^ \*+ Title \*+/,/^\+\-+ MEMORY/p' $seedrun.castep)
         #echo "$input"; exit 1
 
-        [[ -z $input ]] && echo "Input parameters not found ..." && exit 1
+        [[ -z $input ]] && echo "Input parameters not found ..." && continue
 
 
         ## parse General Parameters
@@ -179,12 +180,14 @@ function parsing {
         ## parse Geometry Optimization Parameters
 
         fixed_npw=''
+        geom_spin_fix=''
         geom_energy_tol=''
         geom_force_tol=''
         geom_disp_tol=''
         geom_stress_tol=''
 
         fixed_npw=$(echo "$input" | grep "variable cell method" | head -1 | awk 'BEGIN {FS=":"} {print $2}' | sed -e 's/^ *//g' -e 's/ *$//g')
+        geom_spin_fix=$(echo "$input" | sed -n '/^  with spin/p' | head -1 | awk 'BEGIN {FS="for all steps"} {print $1}' | awk '{print $NF}')
         geom_energy_tol=$(echo "$input" | grep "total energy convergence tolerance" | head -1 | awk 'BEGIN {FS=":"} {print $2}' | awk '{print $1}')
         geom_force_tol=$(echo "$input" | grep "max ionic |force| tolerance" | head -1 | awk 'BEGIN {FS=":"} {print $2}' | awk '{print $1}')
         geom_disp_tol=$(echo "$input" | grep "max ionic |displacement| tolerance" | head -1 | awk 'BEGIN {FS=":"} {print $2}' | awk '{print $1}')
@@ -364,14 +367,14 @@ function parsing {
         ## check if geometry optimization is done successfully
 
         stat=''
-        if [[ $(tail -20 $seedsplit.castep | grep "Total time          = " | awk '{print $1}') != "Total" ]]; then
+        if [[ $(tail -20 $seedrun.castep | grep "Total time          = " | awk '{print $1}') != "Total" ]]; then
             stat='ongoing'
         elif [[ $task == 'single point energy' ]]; then
             stat='NULL'
         elif [[ $task == 'geometry optimization' ]]; then
-            if [[ $(sed -n '/Geometry optimization/p' $seedsplit.castep | sed -n '/failed/p' | wc -l) -eq 1 ]]; then
+            if [[ $(sed -n '/Geometry optimization/p' $seedrun.castep | sed -n '/failed/p' | wc -l) -eq 1 ]]; then
                 stat='failed'
-            elif [[ $(sed -n '/Geometry optimization/p' $seedsplit.castep | sed -n '/completed/p' | wc -l) -eq 1 ]]; then
+            elif [[ $(sed -n '/Geometry optimization/p' $seedrun.castep | sed -n '/completed/p' | wc -l) -eq 1 ]]; then
                 stat='completed'
             else
                 stat='error-checkfile'
@@ -380,16 +383,16 @@ function parsing {
             echo "check task" && exit 1
         fi
 
-        niter=$(sed -n '/LBFGS: finished iteration/p' $seedsplit.castep | tail -n 1 | awk '{print $4}')
+        niter=$(sed -n '/LBFGS: finished iteration/p' $seedrun.castep | tail -n 1 | awk '{print $4}')
         [[ -z $niter ]] && niter='NaN'
 
         ## parse final configuration
 
         fconfig=''
         if [[ $task == 'single point energy' ]]; then
-            fconfig=$(cat $seedsplit.castep)
+            fconfig=$(cat $seedrun.castep)
         elif [[ $task == 'geometry optimization' ]]; then
-            fconfig=$(sed -n '/LBFGS: Final Configuration/,/Total time          =/p' $seedsplit.castep)
+            fconfig=$(sed -n '/LBFGS: Final Configuration/,/Total time          =/p' $seedrun.castep)
         fi
         
         [[ -z $fconfig ]] && echo "Final Configuration not found ..." && continue
@@ -445,18 +448,18 @@ function parsing {
 
         #spin=''
         #modspin=''
-        #spin=$(grep " Spin Den" $seedsplit.castep 2> /dev/null | tail -1 | awk '{print $5}')
-        #modspin=$(grep " |Spin Den" $seedsplit.castep 2> /dev/null | tail -1 | awk '{print $5}')
+        #spin=$(grep " Spin Den" $seedrun.castep 2> /dev/null | tail -1 | awk '{print $5}')
+        #modspin=$(grep " |Spin Den" $seedrun.castep 2> /dev/null | tail -1 | awk '{print $5}')
 
 
         ## parse Mulliken Spin (atom)
 
         echo "$fconfig" | sed -n '/Total   Charge(e)   Spin(hbar\/2)/,/Spin       Length (A)/p' \
-         | sed '/==/,/==/!d;//d' | grep -v "dn" | tail -n $nions | awk '{print $1, $10}' > mullikenspin.dat
+         | sed '/==/,/==/!d;//d' | grep -v "dn" | tail -n $nions | awk '{print $1, $10}' > data-mullikenspin.dat
 
         #cat mullikenspin.dat | awk '{printf "%s=%.2f\n", $1, $2}' | sort -k 1 -u
 
-        ion_spin=$(cat mullikenspin.dat | awk '{printf "%s=%.2f\n", $1, $2}' | sort -k 1 -u | awk '{printf "%s, ",$1}')
+        ion_spin=$(cat data-mullikenspin.dat | awk '{printf "%s=%.2f\n", $1, $2}' | sort -k 1 -u | awk '{printf "%s, ",$1}')
 
 
         # save as tsv
@@ -508,22 +511,25 @@ function parsing {
 
         header='false'
 
-        castep2res $seedsplit > $seedsplit-out.res
+        castep2res $seedrun > $seedrun-out.res
     done
 
     ## generate res file ...
 
     castep2res $seed > $seed-out.res
 
-    echo && catcsv data-input-param.tsv && echo
-    echo && catcsv data-input-cell.tsv && echo
-    echo && catcsv data-output.tsv && echo 
-
     echo "for copying to sheet..."
 
     echo && cat data-input-param.tsv && echo
     echo && cat data-input-cell.tsv && echo
     echo && cat data-output.tsv && echo 
+
+    echo "for pretty print..."
+
+    echo && catcsv data-input-param.tsv && echo
+    echo && catcsv data-input-cell.tsv && echo
+    echo && catcsv data-output.tsv && echo 
+
 }
 
 
diff --git a/bin/param-MS b/bin/param-MS
--- a/bin/param-MS
+++ b/bin/param-MS
@@ -3,7 +3,7 @@
 set -e
 
 
-if [[ $# -ne 1 ]]; then
+if [[ $# -ne 2 ]]; then
     echo "usage: $(basename $0) <seed> <keep>"
     echo "keep  : 0: remove 1:keep"
     exit 1
@@ -15,25 +15,36 @@ keep=$2
 echo "Convert .param generated from MS to my style"
 
 
-echo
-echo "Generarate seed-gencell.param"
-echo
+## checks before proceeding
+
+[[ ! -f $seed.param ]] && echo "$seed.param not found" && exit 1
+
+# backup
+
+md5=`md5sum $seed.param | cut -c 1-8`
+cp $seed.param $seed.param.$md5
+
+
+# generated seed-gencell.param
+
+echo -e "\nGenerarate $seed-gencell.param\n"
 param-gen-gencell $seed
 
-echo
-echo "Generarate seed-default.param"
-echo
+# generated seed-default.param
+
+echo -e "\nGenerarate $seed-default.param\n"
 param-gen-default $seed
 
+# compare parameters
+
+echo -e "\ncompare param\n"
 param-comparison $seed-gencell $seed
 mv $seed.param.cmp $seed.param
 
+echo -e "\ncompare param\n"
 param-comparison $seed-default $seed
 mv $seed.param.cmp $seed.param
 
 sed -i 's/nextra_bands/#nextra_bands/' $seed.param
-
-echo "## added" >> $seed.param
-echo "write_cif_structure       : true" >> $seed.param
 
 [[ $keep == "1" ]] && rm -rf *$seed-gencell.param* *$seed-default.param*
diff --git a/bin/param-comparison b/bin/param-comparison
--- a/bin/param-comparison
+++ b/bin/param-comparison
@@ -26,6 +26,16 @@ seed=$2 # seed.param
 
 rm -f $seed.param.cmp
 
+if [[ $(which castep 2>/dev/null | wc -l) -ne 0 ]]
+then
+    executable='castep'
+elif [[ $(which castep.mpi 2>/dev/null | wc -l) -ne 0 ]]
+then
+    executable='castep.mpi'
+else
+    echo "castep not found" && exit 1
+fi
+
 param-clean $ref 1> /dev/null
 param-clean $seed 1> /dev/null
 
@@ -46,7 +56,7 @@ do
     if [[ `sed -n "/^$key_ref /p" $seed.param | wc -l` -eq 1 ]]; then
 
         # Get the value associated with the keyword
-        val_type=`castep -h $key_ref | grep 'Type:' | awk '{print $2}'`
+        val_type=`$executable -h $key_ref | grep 'Type:' | awk '{print $2}'`
         val=`cat $seed.param | sed -n "/^$key_ref /p" | awk 'BEGIN {FS=":"} {print $2}' | awk '{print $1}'`;
 
         # Check if the values are the same
@@ -87,6 +97,6 @@ do
         
 done
 
-cat $seed.param.cmp
+#cat $seed.param.cmp
 
 exit 0
diff --git a/bin/param-gen-default b/bin/param-gen-default
--- a/bin/param-gen-default
+++ b/bin/param-gen-default
@@ -48,9 +48,20 @@ echo -e $endcolor
 
 ## loop over (keyword and value) pairs in seed.param
 
+if [[ $(which castep 2>/dev/null | wc -l) -ne 0 ]]
+then
+    executable='castep'
+elif [[ $(which castep.mpi 2>/dev/null | wc -l) -ne 0 ]]
+then
+    executable='castep.mpi'
+else
+    echo "castep not found" && exit 1
+fi
+
 for key in $(awk 'BEGIN {FS=":"} {print $1}' $seed.param | awk '{print tolower($1)}')
 do
-    default=$(castep -h $key | grep 'Default value : ' | awk 'BEGIN {FS=": "} {print tolower($2)}')
+        
+    default=$($executable -h $key | grep 'Default value : ' | awk 'BEGIN {FS=": "} {print tolower($2)}')
     val=$default
 
     [[ $key == 'spin_polarized' ]] && val='true'
@@ -67,6 +78,6 @@ do
     [[ $val != $default ]] && printf "%-25s : %s\n" $key "$val ## $default" >> $seed-default.param
 done
 
-cat $seed-default.param
+#cat $seed-default.param
 
 exit 0
diff --git a/bin/param-tol b/bin/param-tol
--- a/bin/param-tol
+++ b/bin/param-tol
@@ -10,7 +10,10 @@ function usage {
     echo 1>&2 -e "usage: $(basename $0) [quality]" 2>&1
     echo 1>&2 -e $endcolor
     echo 1>&2 "$(basename $0)  express"
+    echo 1>&2 "$(basename $0)  coarse"
     echo 1>&2 "$(basename $0)  default"
+    echo 1>&2 "$(basename $0)  medium"
+    echo 1>&2 "$(basename $0)  fine"
     echo 1>&2 "$(basename $0)  ultrafine"
     echo 1>&2 
     exit 1
@@ -23,7 +26,7 @@ if [ $# -lt 1 ]; then
 fi
 
 case $1 in
-    express | default | ultrafine)
+    express | coarse | default | medium | fine | ultrafine)
         quality=$1
         ;;
     *)
@@ -38,31 +41,86 @@ for seed in $(ls *.param | awk 'BEGIN {FS=".param"} {print $1}')
 do
     echo "$seed.param"
 
+    [[ $(sed -n '/^elec_energy_tol /p' $seed.param | wc -l) -gt 1 ]] && echo "Error: check elec_energy_tol keyword" && exit 1
+    [[ $(sed -n '/^geom_energy_tol /p' $seed.param | wc -l) -gt 1 ]] && echo "Error: check elec_energy_tol keyword" && exit 1
+    [[ $(sed -n '/^geom_force_tol /p'  $seed.param | wc -l) -gt 1 ]] && echo "Error: check elec_energy_tol keyword" && exit 1
+    [[ $(sed -n '/^geom_stress_tol /p' $seed.param | wc -l) -gt 1 ]] && echo "Error: check elec_energy_tol keyword" && exit 1
+    [[ $(sed -n '/^geom_disp_tol /p'   $seed.param | wc -l) -gt 1 ]] && echo "Error: check elec_energy_tol keyword" && exit 1
+
+    [[ $(sed -n '/^elec_energy_tol /p'      $seed.param | wc -l) -lt 1 ]] && echo "elec_energy_tol : "      >> $seed.param
+    [[ $(sed -n '/^elec_eigenvalue_tol /p'  $seed.param | wc -l) -lt 1 ]] && echo "elec_eigenvalue_tol : "  >> $seed.param
+    [[ $(sed -n '/^elec_convergence_win /p' $seed.param | wc -l) -lt 1 ]] && echo "elec_convergence_win : " >> $seed.param
+    [[ $(sed -n '/^geom_energy_tol /p'      $seed.param | wc -l) -lt 1 ]] && echo "geom_energy_tol : "      >> $seed.param
+    [[ $(sed -n '/^geom_force_tol /p'       $seed.param | wc -l) -lt 1 ]] && echo "geom_force_tol : "       >> $seed.param
+    [[ $(sed -n '/^geom_stress_tol /p'      $seed.param | wc -l) -lt 1 ]] && echo "geom_stress_tol : "      >> $seed.param
+    [[ $(sed -n '/^geom_disp_tol /p'        $seed.param | wc -l) -lt 1 ]] && echo "geom_disp_tol : "        >> $seed.param
+
     sed -i 's/^#elec_energy_tol /elec_energy_tol /' $seed.param
     sed -i 's/^#geom_energy_tol /geom_energy_tol /' $seed.param
     sed -i 's/^#geom_force_tol /geom_force_tol /' $seed.param
     sed -i 's/^#geom_stress_tol /geom_stress_tol /' $seed.param
     sed -i 's/^#geom_disp_tol /geom_disp_tol /' $seed.param
 
-    if [[ $quality == "express" ]]
+    if [[ $quality == "express" ]] # MS express quality
     then
         sed -i 's/^elec_energy_tol [[:print:]]*/elec_energy_tol           : 1.0e-04/' $seed.param
-        sed -i 's/^geom_energy_tol [[:print:]]*/geom_energy_tol           : 1.0e-03/' $seed.param
-        sed -i 's/^geom_force_tol [[:print:]]*/geom_force_tol            : 100/' $seed.param
-        sed -i 's/^geom_stress_tol [[:print:]]*/geom_stress_tol           : 100/' $seed.param
-        sed -i 's/^geom_disp_tol [[:print:]]*/geom_disp_tol             : 100/' $seed.param
+        sed -i 's/^elec_eigenvalue_tol [[:print:]]*/elec_eigenvalue_tol       : 1.0e-04/' $seed.param
+        sed -i 's/^elec_convergence_win [[:print:]]*/elec_convergence_win      : 2/' $seed.param
+        sed -i 's/^geom_energy_tol [[:print:]]*/geom_energy_tol           : 5.0e-04/' $seed.param
+        sed -i 's/^geom_force_tol [[:print:]]*/geom_force_tol            : 0.5/' $seed.param
+        sed -i 's/^geom_stress_tol [[:print:]]*/geom_stress_tol           : 1.0/' $seed.param
+        sed -i 's/^geom_disp_tol [[:print:]]*/geom_disp_tol             : 0.03/' $seed.param
+        #sed -i 's/^elec_energy_tol [[:print:]]*/elec_energy_tol           : 1.0e-04/' $seed.param
+        #sed -i 's/^geom_energy_tol [[:print:]]*/geom_energy_tol           : 1.0e-03/' $seed.param
+        #sed -i 's/^geom_force_tol [[:print:]]*/geom_force_tol            : 100/' $seed.param
+        #sed -i 's/^geom_stress_tol [[:print:]]*/geom_stress_tol           : 100/' $seed.param
+        #sed -i 's/^geom_disp_tol [[:print:]]*/geom_disp_tol             : 100/' $seed.param
 
-    elif [[ $quality == "default" ]]
+    elif [[ $quality == "coarse" ]] # MS coarse quality
     then
         sed -i 's/^elec_energy_tol [[:print:]]*/elec_energy_tol           : 1.0e-05/' $seed.param
+        sed -i '/^elec_eigenvalue_tol [[:print:]]*/d' $seed.param
+        sed -i '/^elec_convergence_win [[:print:]]*/d' $seed.param
+        sed -i 's/^geom_energy_tol [[:print:]]*/geom_energy_tol           : 5.0e-05/' $seed.param
+        sed -i 's/^geom_force_tol [[:print:]]*/geom_force_tol            : 0.1/' $seed.param
+        sed -i 's/^geom_stress_tol [[:print:]]*/geom_stress_tol           : 0.2/' $seed.param
+        sed -i 's/^geom_disp_tol [[:print:]]*/geom_disp_tol             : 0.005/' $seed.param
+
+    elif [[ $quality == "default" ]] # CASTEP default
+    then
+        sed -i 's/^elec_energy_tol [[:print:]]*/elec_energy_tol           : 1.0e-05/' $seed.param
+        sed -i '/^elec_eigenvalue_tol [[:print:]]*/d' $seed.param
+        sed -i '/^elec_convergence_win [[:print:]]*/d' $seed.param
         sed -i 's/^geom_energy_tol [[:print:]]*/geom_energy_tol           : 2.0e-05/' $seed.param
         sed -i 's/^geom_force_tol [[:print:]]*/geom_force_tol            : 0.05/' $seed.param
         sed -i 's/^geom_stress_tol [[:print:]]*/geom_stress_tol           : 0.1/' $seed.param
         sed -i 's/^geom_disp_tol [[:print:]]*/geom_disp_tol             : 0.001/' $seed.param
 
-    elif [[ $quality == "ultrafine" ]]
+    elif [[ $quality == "medium" ]] # MS medium quality
+    then
+        sed -i 's/^elec_energy_tol [[:print:]]*/elec_energy_tol           : 2.0e-06/' $seed.param
+        sed -i '/^elec_eigenvalue_tol [[:print:]]*/d' $seed.param
+        sed -i '/^elec_convergence_win [[:print:]]*/d' $seed.param
+        sed -i 's/^geom_energy_tol [[:print:]]*/geom_energy_tol           : 2.0e-05/' $seed.param
+        sed -i 's/^geom_force_tol [[:print:]]*/geom_force_tol            : 0.05/' $seed.param
+        sed -i 's/^geom_stress_tol [[:print:]]*/geom_stress_tol           : 0.1/' $seed.param
+        sed -i 's/^geom_disp_tol [[:print:]]*/geom_disp_tol             : 0.002/' $seed.param
+
+    elif [[ $quality == "fine" ]] # MS fine quality
+    then
+        sed -i 's/^elec_energy_tol [[:print:]]*/elec_energy_tol           : 1.0e-06/' $seed.param
+        sed -i '/^elec_eigenvalue_tol [[:print:]]*/d' $seed.param
+        sed -i '/^elec_convergence_win [[:print:]]*/d' $seed.param
+        sed -i 's/^geom_energy_tol [[:print:]]*/geom_energy_tol           : 1.0e-05/' $seed.param
+        sed -i 's/^geom_force_tol [[:print:]]*/geom_force_tol            : 0.03/' $seed.param
+        sed -i 's/^geom_stress_tol [[:print:]]*/geom_stress_tol           : 0.05/' $seed.param
+        sed -i 's/^geom_disp_tol [[:print:]]*/geom_disp_tol             : 0.001/' $seed.param
+
+    elif [[ $quality == "ultrafine" ]] # MS ultrafine quality
     then
         sed -i 's/^elec_energy_tol [[:print:]]*/elec_energy_tol           : 5.0e-07/' $seed.param
+        sed -i '/^elec_eigenvalue_tol [[:print:]]*/d' $seed.param
+        sed -i '/^elec_convergence_win [[:print:]]*/d' $seed.param
         sed -i 's/^geom_energy_tol [[:print:]]*/geom_energy_tol           : 5.0e-06/' $seed.param
         sed -i 's/^geom_force_tol [[:print:]]*/geom_force_tol            : 0.01/' $seed.param
         sed -i 's/^geom_stress_tol [[:print:]]*/geom_stress_tol           : 0.02/' $seed.param
